{"name": "testFour", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def testFour():\n        print(\"I am method four\")\n>       assert False\nE       assert False\n\ntest_allure.py:19: AssertionError"}, "start": 1671358768314, "stop": 1671358768314, "uuid": "46e64667-b328-4edf-bccb-f6b4c3fc5d3f", "historyId": "26384c762c73eaa647d396a20cd99394", "testCaseId": "6f817e9cdb6db20ce56e9ab1d77a2236", "fullName": "test_allure#testFour", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "NahidNiloy14"}, {"name": "thread", "value": "13844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}